// Puts everything the browser needs to run the Python core into public/, which is otherwise
// empty and is not checked in. Two kinds of thing land there:
//
//   public/autocircuit-src.zip   the package itself, built by the same make_zip.py the Pyodide
//                                benchmark uses -- one archive builder, so the site and the
//                                benchmark cannot ship different cores -- and then handed to
//                                precompile.mjs, which writes it out again with its bytecode.
//   public/pyodide/              the Pyodide distribution *including the numpy and scipy
//                                wheels*, which the npm package does not carry. Copied here so
//                                loadPackage resolves them beside pyodide-lock.json instead of
//                                reaching for a CDN: that is what makes the site work offline
//                                and what keeps a development machine off the network.
//   public/pyodide-bytecode-*.zip  bytecode for the stdlib, numpy, scipy and this package, so a
//                                visitor's browser does not compile Python it could have been
//                                handed compiled. One overlay per wheel, because the page
//                                installs them in two stages. Written by precompile.mjs, which
//                                also rewrites the two archives above; see its header.
//   public/samples/              example spectra generated by the project's own `simulate`
//                                CLI, not checked in: the site must not ship data the CLI would
//                                not itself produce. See buildSamples() below.
//
// Run by `npm run dev` and `npm run build`, so a change to the Python source is picked up
// without anyone having to remember a second command.
import { createWriteStream } from "node:fs";
import { copyFile, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { precompile } from "./precompile.mjs";
import { SAMPLES } from "./samples.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB = resolve(HERE, "..");
const REPO = resolve(WEB, "..");
const PUBLIC = join(WEB, "public");
// Not in public/: this is precompile.mjs's input, and its output is the archive of the same
// package that the browser fetches. One path for both would make the step's own product decide
// whether the step needs to run.
const SOURCE_ARCHIVE = join(WEB, ".build", "autocircuit-source.zip");
const PYODIDE_OUT = join(PUBLIC, "pyodide");
const PYODIDE_PKG = join(WEB, "node_modules", "pyodide");
const SAMPLES_OUT = join(PUBLIC, "samples");
const PYTHONPATH = join(REPO, "src");

// Everything loadPyodide fetches at run time. The source maps and the bundled consoles are
// deliberately left behind; they are several megabytes of things the site never asks for.
// `python_stdlib.zip` is missing on purpose: precompile.mjs writes that one, and a copy here
// would put a source stdlib back whenever precompile had nothing to rebuild.
const RUNTIME_FILES = ["pyodide.mjs", "pyodide.asm.mjs", "pyodide.asm.wasm", "pyodide-lock.json"];

// The packages the core imports. numpy and scipy are the only runtime dependencies AutoCircuit
// has, which is what makes this list short enough to vendor -- see CLAUDE.md.
const WHEELS = ["numpy", "scipy"];

async function exists(path) {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

function buildSourceArchive() {
  const script = join(REPO, "benchmarks", "pyodide", "make_zip.py");
  const out = SOURCE_ARCHIVE;
  const result = spawnSync("python", [script, "-o", out], { stdio: "inherit" });
  if (result.status !== 0) {
    throw new Error(`make_zip.py failed (exit ${result.status}); is python on PATH?`);
  }
}

async function copyRuntime() {
  await mkdir(PYODIDE_OUT, { recursive: true });
  for (const name of RUNTIME_FILES) {
    await copyFile(join(PYODIDE_PKG, name), join(PYODIDE_OUT, name));
  }
  console.log(`pyodide runtime -> ${PYODIDE_OUT} (${RUNTIME_FILES.length} files)`);
}

async function copyWheels() {
  const lock = JSON.parse(await readFile(join(PYODIDE_PKG, "pyodide-lock.json"), "utf8"));
  const version = JSON.parse(await readFile(join(PYODIDE_PKG, "package.json"), "utf8")).version;
  for (const name of WHEELS) {
    const entry = lock.packages[name];
    if (!entry) throw new Error(`pyodide-lock.json has no package ${name}`);
    const target = join(PYODIDE_OUT, entry.file_name);
    if (await exists(target)) continue;

    // The npm package ships the runtime but not the wheels, except that running Pyodide under
    // Node once leaves them cached in its directory. Prefer whatever is already on disk --
    // node_modules here, then the benchmark's -- and only then the network.
    const local = [
      join(PYODIDE_PKG, entry.file_name),
      join(REPO, "benchmarks", "pyodide", "node_modules", "pyodide", entry.file_name),
    ];
    let copied = false;
    for (const candidate of local) {
      if (await exists(candidate)) {
        await copyFile(candidate, target);
        console.log(`${entry.file_name} <- ${candidate}`);
        copied = true;
        break;
      }
    }
    if (copied) continue;

    const url = `https://cdn.jsdelivr.net/pyodide/v${version}/full/${entry.file_name}`;
    console.log(`${entry.file_name} <- ${url}`);
    const response = await fetch(url);
    if (!response.ok) throw new Error(`${url} -> HTTP ${response.status}`);
    await pipeline(Readable.fromWeb(response.body), createWriteStream(target));
  }
}

// Generates the example datasets by running the project's own `simulate` CLI -- the same
// command a user would type -- rather than checking in pre-made CSVs, so the site can never
// ship data that command would not itself produce.
// `String(1e-6)` is "0.000001", which is the same number and a worse thing to read in a command
// somebody is meant to be able to retype. JavaScript only reaches for exponential notation below
// 1e-7; the parameters here are capacitances and inductances, so it is asked for sooner.
function formatValue(value) {
  return value !== 0 && Math.abs(value) < 1e-3 ? value.toExponential() : String(value);
}

async function buildSamples() {
  await mkdir(SAMPLES_OUT, { recursive: true });
  const env = { ...process.env, PYTHONPATH };
  const index = [];
  for (const sample of SAMPLES) {
    const file = `samples/${sample.id}.csv`;
    const out = join(PUBLIC, file);
    // Path relative to the repo root, as a reader who has just cloned the repo would type it --
    // not the absolute path this machine happens to use, which nobody else could reproduce.
    const outPortable = `web/public/${file}`;
    const paramArgs = Object.entries(sample.params).flatMap(([name, value]) => [
      "-p",
      `${name}=${formatValue(value)}`,
    ]);
    const commonArgs = [
      "-m",
      "autocircuit",
      "simulate",
      "-c",
      sample.circuit,
      ...paramArgs,
      "--fmin",
      String(sample.fMin),
      "--fmax",
      String(sample.fMax),
      "--points-per-decade",
      String(sample.pointsPerDecade),
      "--noise",
      String(sample.noise),
      "--seed",
      String(sample.seed),
    ];
    const args = [...commonArgs, "-o", out];
    const command = ["python", ...commonArgs, "-o", outPortable].join(" ");
    const result = spawnSync("python", args, { stdio: "inherit", env });
    if (result.status !== 0) {
      throw new Error(`simulate failed for sample "${sample.id}" (exit ${result.status})`);
    }
    index.push({ ...sample, file, command });
    console.log(`sample ${sample.id} -> ${out}`);
  }
  await writeFile(join(SAMPLES_OUT, "index.json"), JSON.stringify(index, null, 2), "utf8");
  console.log(`samples index -> ${join(SAMPLES_OUT, "index.json")} (${index.length} entries)`);
}

await mkdir(PUBLIC, { recursive: true });
await mkdir(dirname(SOURCE_ARCHIVE), { recursive: true });
buildSourceArchive();
await copyRuntime();
await copyWheels();
// After the archive and the wheels, because it compiles both; before the samples, because they
// do not depend on it. This is what writes public/autocircuit-src.zip.
await precompile(PUBLIC, PYODIDE_PKG, SOURCE_ARCHIVE);
await buildSamples();
