// Proves the browser's Python path works, without a browser.
//
// Node and a browser load the identical Pyodide wasm build, so everything between "bytes land
// in the filesystem" and "the bridge answers" can be checked here: the vendored distribution in
// public/ is the one loaded, the source archive in public/ is the one unpacked, and the file is
// read through the same FS.writeFile the worker uses. What this cannot cover is the worker
// message loop itself, which needs the real browser.
//
//   npm run smoke
import { readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { loadPyodide } from "pyodide";

const HERE = dirname(fileURLToPath(import.meta.url));
const PUBLIC = resolve(HERE, "..", "public");

// A four-point spectrum is enough to exercise the reader, the sniffer and the wire format.
// Lin-KK needs more than that to say anything, so the validation check below uses a longer one
// generated in Python from the same simulate() the CLI uses.
const CSV = `Frequency,Re(Z),Im(Z)
100,0.01,-1591.549
1000,0.01,-159.155
10000,0.01,-15.915
100000,0.01,-1.592
`;

const failures = [];

function check(name, condition, detail = "") {
  if (condition) {
    console.log(`  ok   ${name}`);
  } else {
    console.log(`  FAIL ${name}${detail ? ` -- ${detail}` : ""}`);
    failures.push(name);
  }
}

const started = Date.now();
const pyodide = await loadPyodide({ indexURL: join(PUBLIC, "pyodide"), stdout: () => {} });
await pyodide.loadPackage(["numpy", "scipy"]);
// Wrapped: unpackArchive rejects a Node Buffer with "Unknown typed array type 'Buffer'".
pyodide.unpackArchive(new Uint8Array(readFileSync(join(PUBLIC, "autocircuit-src.zip"))), "zip", {
  extractDir: "/autocircuit-src",
});
pyodide.runPython(`
import sys
sys.path.insert(0, "/autocircuit-src")
from autocircuit.web import handle
`);
const handle = pyodide.globals.get("handle");
console.log(`loaded in ${((Date.now() - started) / 1000).toFixed(1)} s`);

const ask = (request) => JSON.parse(handle(JSON.stringify(request)));

console.log("version");
const version = ask({ op: "version" });
check("version answers", version.ok === true, JSON.stringify(version));
check("bridge version is 2", version.result?.bridge === 2);
check(
  "all four readers are present",
  JSON.stringify(version.result?.formats) ===
    JSON.stringify(["generic_csv", "keysight", "touchstone", "zview"]),
  JSON.stringify(version.result?.formats),
);

console.log("read");
pyodide.FS.mkdirTree("/uploads/1");
pyodide.FS.writeFile("/uploads/1/example.csv", new TextEncoder().encode(CSV));
const read = ask({ op: "read", path: "/uploads/1/example.csv" });
check("read succeeds", read.ok === true, JSON.stringify(read.error));
const spectrum = read.result?.spectra?.[0];
check("one sweep, four points", read.result?.spectra?.length === 1 && spectrum?.f.data.length === 4);
check("format was sniffed as generic_csv", spectrum?.metadata?.format === "generic_csv");
check(
  "the imaginary part kept its sign",
  spectrum?.z.im[0] === -1591.549,
  JSON.stringify(spectrum?.z.im),
);

console.log("trim");
const trimmed = ask({ op: "trim", spectrum, f_min: 1000, f_max: 10000 });
check("trim succeeds", trimmed.ok === true, JSON.stringify(trimmed.error));
check("two points survive", trimmed.result?.spectrum.f.data.length === 2);
const empty = ask({ op: "trim", spectrum, f_min: 1e12, f_max: null });
check("an empty window is an error response, not a crash", empty.ok === false);
check(
  "and it says what went wrong",
  empty.error?.message === "frequency window selects no points",
  JSON.stringify(empty.error),
);

console.log("validate");
// A real spectrum, generated by the same code the CLI simulates with, because Lin-KK on four
// points has nothing to say.
pyodide.runPython(`
import json
from autocircuit.core.simulate import log_frequencies, simulate

_spectrum = simulate(
    "C1-R1-L1",
    log_frequencies(1e2, 1e9, 10),
    {"C1.C": 1e-6, "R1.R": 1e-2, "L1.L": 5e-10},
    noise=0.01,
    seed=0,
)
_wire = json.dumps(_spectrum.to_wire())
`);
const simulated = JSON.parse(pyodide.globals.get("_wire"));
const validation = ask({ op: "validate", spectrum: simulated });
check("validate succeeds", validation.ok === true, JSON.stringify(validation.error));
const kk = validation.result?.validation;
check("the verdict is a pass on clean synthetic data", kk?.passed === true);
check("the residual pattern is random", kk?.systematic === false);
check("the summary text travelled", typeof kk?.summary === "string" && kk.summary.includes("Lin-KK"));

console.log("circuit");
const catalogue = ask({ op: "elements" });
check("elements answers", catalogue.ok === true, JSON.stringify(catalogue.error));
check(
  "the palette is the registry, not a copy of it",
  catalogue.result?.elements?.some((element) => element.code === "CPE") === true,
);
check(
  "the pools are the ones --pool offers",
  JSON.stringify(Object.keys(catalogue.result?.pools ?? {})) ===
    JSON.stringify(["default", "component", "electrochemical"]),
);

const described = ask({ op: "circuit", circuit: "C1-R1-L1", spectrum: simulated });
check("circuit parses", described.ok === true, JSON.stringify(described.error));
check("its tree is a series of three", described.result?.tree?.children?.length === 3);
check(
  "each parameter carries the interval the fitter searches",
  described.result?.params?.every((p) => typeof p.start === "number" && p.lower < p.upper) === true,
);
const broken = ask({ op: "circuit", circuit: "C1-p(R2" });
check("a syntax error is an error response, not a crash", broken.ok === false);

const edited = ask({ op: "edit", circuit: "C1-R1", path: [1], action: "parallel", code: "C" });
check("an edit answers with the circuit it produced", edited.result?.circuit === "C1-p(R1,C2)");
const collapsed = ask({
  op: "edit",
  circuit: "C1-R1-p(R2,C2)",
  path: [2, 1],
  action: "remove",
});
check(
  "deleting one branch of a pair collapses the block",
  collapsed.result?.circuit === "C1-R1-R2",
  JSON.stringify(collapsed),
);

console.log("preview and fit");
const preview = ask({ op: "preview", circuit: "C1-R1-L1", spectrum: simulated });
check("preview answers", preview.ok === true, JSON.stringify(preview.error));
check(
  "it evaluates at every measured frequency",
  preview.result?.z_model?.re.length === simulated.f.data.length,
);
const fitted = ask({ op: "fit", circuit: "C1-R1-L1", spectrum: simulated, restarts: 2 });
check("fit answers", fitted.ok === true, JSON.stringify(fitted.error));
check("it converged", fitted.result?.fit?.success === true, fitted.result?.fit?.message);
check(
  "it recovered the capacitance it was generated from",
  Math.abs(fitted.result?.fit?.values.data[0] / 1e-6 - 1) < 0.05,
  JSON.stringify(fitted.result?.fit?.values.data),
);
check(
  "the residuals arrive already split, one value per point",
  fitted.result?.residual_real?.data.length === simulated.f.data.length &&
    fitted.result?.residual_imag?.data.length === simulated.f.data.length,
);
check(
  "the report text travelled",
  typeof fitted.result?.summary === "string" && fitted.result.summary.includes("chi^2"),
);

console.log("errors");
check("a missing file is an error response", ask({ op: "read", path: "/nope.csv" }).ok === false);
check("an unknown operation is an error response", ask({ op: "nonsense" }).ok === false);
check("malformed JSON is an error response", JSON.parse(handle("{not json")).ok === false);

console.log(failures.length === 0 ? "\nall checks passed" : `\n${failures.length} FAILED`);
process.exit(failures.length === 0 ? 0 : 1);
